# Name used metrics
name: ActionTracker

# Retry policy for jobs taking to long
retryPolicy:

  # The max duration a github action job can remain in a Queued state before retrying to process it.
  # The job will be sent to the retry topic
  maxJobInQueuedInMinutes: 6

  # The minimum duration between attempting subsequent retries for a job.
  maxTimeBtwRetriesInMinutes: 6

  # Max retries for a job
  maxRetries: 3

# Kafka configurations
kafka:

  # The retry Topic name. Jobs that have been queued past a certain point will be retried.
  # The ActionTracker will produce messages to this topic.
  retryTopic: retry

  # Action Tracker polls from this topic for incoming github action jobs.
  webhookTopic: webhook

  # Kafka broker connection information
  broker: localhost:9092

  # Consumer Group for kafka Queue. Please ensure this is unique.
  # Warning: please be careful updating the consumerGroupId. You can cause older jobs to attempt to
  #     reprocess if you haven't cleared the topic.
  consumerGroupId: actiontracker

# Github Configurations
github:

  # This is the github action runner group Name. ActionTracker confirms that the group name matches before retrying github action job.
  groupName: "prod"

