
name: gcp-1-autoscaler
computeType: gcp
logLevel: "info" # info | warn | debug | verbose. verbose option means debug mode but also dependencies are in debug mode. Of course  as a java springboot developer you can override these settings easily
standalone: false # "default false". turns off kafka queue listener
kafka:
  retryTopic: retry
  webhookTopic: webhook
  broker: kafka:9093
  consumerGroupId: aws-autoscaler

github:
  groupName: "prod"
  organizationName: "bourgeoisie-whacker"
  token:
  webhookSecret: test

compute:
  defaultSettings:
    idleScaleDownInMinutes: 10
    projectId:
    region:
    subnet:
    vpc:
    zones:
    diskSettings:
      size: "20" # in gigs
    instanceType:
    maxInstanceCount: 10
  defaultActionPool:
    name: default-pool
  actionPools:
    - name: test
      instanceType: n2d-standard-2
      maxInstanceCount: 1
      subnet: subnet-1234
      diskSettings:
        size: 12

