name: aws-1-autoscaler
computeType: aws
logLevel: "info" # info | warn | debug | verbose. verbose option means debug mode but also dependencies are in debug mode. Of course  as a java springboot developer you can override these settings easily
standalone: false # "default false". turns off kafka queue listener

kafka:
  retryTopic: retry
  webhookTopic: webhook
  broker: kafka:9093
  consumerGroupId: aws-autoscaler

github:
  groupName: "prod"
  organizationName: "bourgeoisie-whacker"
  token:  ${GITHUB_TOKEN}

compute:
  defaultSettings:
    idleScaleDownInMinutes:
    region:
    subnet:
    securityGroup:
    diskSettings:
      type:
      size:
    instanceType:
    maxInstanceCount:
    keyPairName:
  defaultActionPool:
    name: default-pool
  actionPools:
    - name: test



