name: webhook
kafka:
  webhookTopic: webhook
  broker: localhost:9092
github:
  webhookSecret: test
#server:
#  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: mappings
logging:
  level:
    com:
      nimbus: debug