# Application name for metrics reporting
name: webhook

# Kafka integration settings
kafka:
  # Writes incoming github webhook messages to this topic
  webhookTopic: webhook
  # Kafka broker address
  broker: localhost:9092
# GitHub integration settings
github:
  # Optional webhook secret to verify incoming requests.
  webhookSecret: test

# HTTP server configuration
server:
  # Port for both metrics endpoint and webhook server
  port: 8082