apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
   {{- include "webhook.labels" . | nindent 4}}

data:
  {{ .Values.webhook.configMap.nimbusRun.keyName}}: |
    name: {{.Values.webhook.settings.name}}
    kafka:
      webhookTopic: {{.Values.kafka.webhookTopic.name}}
      broker: {{include "kafka-broker-url" .}}
    github:
      webhookSecret: {{ .Values.github.webhookSecret }}
    {{- with .Values.webhook.additionalSettings}}
    {{- toYaml . | nindent 4}}
    {{- end }}

