# Application name for metrics reporting
name: aws-1-autoscaler

# Compute backend to use (e.g., aws, gcp, azure)
computeType: aws

# Application log level (info | warn | debug | fatal).
# These defaults can be overridden via Spring Boot properties.
logLevel: "info"


# Retry policy for jobs taking to long
retryPolicy:

  # The max duration a github action job can remain in a Queued state before retrying to process it.
  # The job will be retried
  maxJobInQueuedInMinutes: 6

  # The minimum duration between attempting subsequent retries for a job.
  maxTimeBtwRetriesInMinutes: 6

  # Max retries for a job
  maxRetries: 3

# GitHub integration settings
github:
  # Environment or runner group label in GitHub
  groupName: "prod"

  # GitHub organization name
  organizationName: "bourgeoisie-whacker"

  # Personal access token with permissions to:
  #  • Create self-hosted runner tokens
  #  • List organization runners
  token: ${GITHUB_TOKEN}

  # Optional webhook secret to verify incoming requests.
  # Only required in standalone mode when using GitHub webhooks.
  webhookSecret: test

  # This is used to redeliver older webhooks that failed to be sent. This is the id of the github webhook
  # Make sure you make this a string otherwise it'll be converted into scientific notation
  webhookId: "565459826"
  # If you have set the webhookId then you can set this to true for the system on startup to resend all failed sent webhooks that were sent TODAY
  replayFailedDeliverOnStartup: true

# HTTP server configuration
server:
  # Port for both metrics endpoint and webhook server
  port: 8080

# Compute instance settings for action pools
compute:
  # Fallback settings applied if not overridden in any action pool
  defaultSettings:
    # Minutes of idle time before scaling down an instance
    # (account for instance boot and runner startup time)
    idleScaleDownInMinutes: 3

    # AWS region for instance provisioning
    region: us-east-1

    # AWS subnet ID for instance networking
    subnet: subnet-257dbf7d

    # AWS security group ID for instance firewall rules
    securityGroup: sg-0189c3298c7be64ca

    # AWS Credentials Profile to used. This will look for the aws credential file at the default location or if you specify the AWS_SHARED_CREDENTIALS_FILE.
    # If you don't specify this value then it will use the DefaultCredential provider to obtain credentials.
    # Please see default credentials provider chain
    # https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html
    credentialsProfile:
    # Disk configuration
    diskSettings:
      # Supported values: gp3, gp2, io2, io1, st1
      type: "gp3"
      # Disk size in GiB
      size: 20

    # EC2 instance type for GitHub runners
    instanceType: t3.medium

    # Maximum number of instances (0 = no limit)
    maxInstanceCount: 10

    # Name of the EC2 key pair to inject for SSH access
    keyPairName: Testers

    # The operating system to be used. See compatibility matrix to see supported version
    os: ubuntu22.04

    # The Central Processor Unit Architecture. Either x64 or ARM64. See compatibility matrix to see supported version.
    architecture: x64
  # Default action pool placeholder (inherits from defaultSettings)
  defaultActionPool:
    name: default-pool

  # Specific action pools (override defaultSettings as needed)
  actionPools:
    - name: t3a.xlarge
      instanceType: t3a.xlarge
      maxInstanceCount: 1
      subnet: subnet-1234
      securityGroup: securityGroup-1234
      diskSettings:
        type: gp2
        size: 4

    - name: c4.2xlarge
      instanceType: c4.2xlarge
      maxInstanceCount: 4

    - name: m8gd.medium
      instanceType: m8gd.medium
      maxInstanceCount: 3
      # Use NVMe storage on this instance type
      isNvme: true

    - name: t3.medium
      instanceType: t3.medium
      maxInstanceCount: 3

    # Example of a pool defined by name only (inherits all defaults)
    - name: haha