name: aws-1-autoscaler
computeType: aws
logLevel: "info" # info | warn | debug | verbose. verbose option means debug mode but also dependencies are in debug mode. Of course  as a java springboot developer you can override these settings easily
standalone: true # "default false". turns off kafka queue listener

kafka:
  retryTopic: retry
  webhookTopic: webhook
  broker: localhost:9092
  consumerGroupId: aws-autoscaler

github:
  groupName: "prod"
  organizationName: "bourgeoisie-whacker"
  token: ${GITHUB_TOKEN}
#  webhookSecret: test

server:
  port: 8080

compute:
  defaultSettings:
    idleScaleDownInMinutes: 3
    region: us-east-1
    subnet: subnet-257dbf7d
    securityGroup: sg-0189c3298c7be64ca
    #    credentialsProfile: #<------- if blank it'll just use the default Credentials provider
    diskSettings:
      type: "gp3" #Possible values gp3 | gp2 | io2 | io1| st1
      size: "20" # in gigs
    instanceType: t3.medium
    maxInstanceCount: 10 # <--no max
    keyPairName: Testers
  defaultActionPool:
    name: default-pool
  actionPools:
    - name: t3a.xlarge
      instanceType: t3a.xlarge
      maxInstanceCount: 1
      subnet: subnet-1234
      securityGroup: securityGroup-1234
      diskSettings:
        type: "gp2"
        size: 4
    - instanceType: c4.2xlarge
      maxInstanceCount: 4
      name: c4.2xlarge
    - instanceType: m8gd.medium
      name: m8gd.medium
      maxInstanceCount: 3
      isNvme: true
    - instanceType: t3.medium
      name: t3.medium
      maxInstanceCount: 3
    - name: haha


