apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "actionTracker.fullname" . }}
  labels:
   {{- include "actionTracker.labels" . | nindent 4}}

data:
  "config.yaml": |
    kafka:
      {{- with .Values.kafka }}
        {{- toYaml . | nindent 8}}
      {{- end }}

    github:
      {{- with .Values.github}}
        {{- toYaml . | nindent 8}}
      {{- end }}

