apiVersion: v2
name: nimbus-run
description: "NimbusRun is an autoscaler for GitHub self-hosted runners that run on virtual machines (AWS, GCP, or your own compute engine). Unlike Kubernetes-only solutions, it brings elastic scaling to VM-based runners, including full scale-to-zero support to eliminate the “cloud idle tax.” With features such as dynamic autoscaling of GitHub Actions runners, support for multiple cloud providers or pluggable backends, retry logic for stuck jobs, and simple deployment via Helm, NimbusRun helps reduce idle compute, improve build efficiency, and prevent unexpected costs on your cloud bill."
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.10
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.3.10"
