name: aws-1-autoscaler
computeType: aws
logLevel: "info" # info | warn | debug | verbose. verbose option means debug mode but also dependencies are in debug mode. Of course  as a java springboot developer you can override these settings easily

github:
  groupName: ""  # prod
  organizationName: ""  # bourgeoisie-whacker
  token: "" # This is the github token with permissions to interact with github actions

compute:
  defaultSettings:
    region: "us-east-1"
    subnet: "" # subnet-id i.e subnet-1234
    securityGroup: "" # security group id i.e sg-1234
    diskSettings:
      type: "gp3" #Possible values gp3 | gp2 | io2 | io1| st1
      size: "20" # in gigs
    instanceType: "t3.medium" # i.e t3.medium
    maxInstanceCount: 10 #
  defaultActionPool:
    name: default-pool
  actionPools:
    - name: test1
      instanceType: t3.medium
    - name: test2
      instanceType: c4.2xlarge