version: "3.9"

services:
  autoscaler:
    image: bourgeoisiehacker/autoscaler:latest
    environment:
#      AWS_ACCESS_KEY_ID: <SETUP> # You can explicitly set AWS environment variables for authentication to AWS
#      AWS_SECRET_ACCESS_KEY: <SETUP> # You can explicitly set AWS environment variables for authentication to AWS
      NIMBUS_RUN_CONFIGURATION_FILE: /opt/config.yaml
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - "./config_examples/autoscaler/config-aws.yaml:/opt/config.yaml"
    depends_on:
      init-topics:
        condition: service_completed_successfully

networks:
  default:
    name: nimbus_run