name: aws-1-autoscaler
computeType: aws
logLevel: "info" # info | warn | debug | verbose. verbose option means debug mode but also dependencies are in debug mode. Of course  as a java springboot developer you can override these settings easily

github:
  groupName: "prod"
  organizationName: "bourgeoisie-whacker"
  token: "" # This is the github token with permissions to interact with github actions

server:
  port: 8081

compute:
  defaultSettings:
    idleScaleDownInMinutes: 10 # This number should higher than 5 atleast. It takes a second for runner service to start
    region: "" # i.e us-east-2
    subnet: "" # subnet-id i.e subnet-1234
    securityGroup: "" # security group id i.e sg-1234
    diskSettings:
      type: "gp3" #Possible values gp3 | gp2 | io2 | io1| st1
      size: "20" # in gigs
    instanceType: "" # i.e t3.medium
    maxInstanceCount: 10 #
  defaultActionPool:
    name: default-pool
  actionPools:
    - name: t3.medium
      instanceType: t3.medium
    - name: big-compute
      instanceType: c4.2xlarge