apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autoscaler.fullname" . }}
  labels:
   {{- include "autoscaler.labels" . | nindent 4}}

data:
  {{.Values.autoscaler.configMap.nimbusRun.keyName}}: |
    name: {{.Values.autoscaler.settings.name}}
    logLevel: {{.Values.autoscaler.settings.logLevel}}
    standalone: {{.Values.standalone}}
    computeType: {{.Values.compute.computeType}}
    kafka:
      retryTopic: {{ .Values.kafka.retryTopic.name }}
      webhookTopic: {{ .Values.kafka.webhookTopic.name }}
      broker: {{ include "kafka-broker-url" . }}
      consumerGroupId: {{ .Values.autoscaler.settings.kafkaConsumerGroup}}
      {{- if .Values.kafka.create}}
      shouldCreateTopics: true
      {{- end }}

    github:
      groupName: {{ .Values.github.groupName }}
      organizationName: {{ .Values.github.organizationName }}
      token: {{ .Values.github.token }}
      webhookSecret: {{ .Values.github.webhookSecret }}

    compute:
      {{- include "autoscaler.computeSettings" . | nindent 8}}
    {{- with .Values.autoscaler.additionalSettings}}
        {{- toYaml . | nindent 4}}
    {{- end }}