apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autoscaler.fullname" . }}
  labels:
   {{- include "autoscaler.labels" . | nindent 4}}

data:
  "config.yaml": |
    name: {{.Values.autoscaler.settings.name}}
    logLevel: {{.Values.autoscaler.settings.logLevel}}
    standalone: {{.Values.standalone}}
    computeType: {{.Values.compute.computeType}}
    kafka:
      {{- with .Values.kafka }}
        {{- toYaml . | nindent 8}}
      {{- end }}

    github:
      {{- with .Values.github}}
        {{- toYaml . | nindent 8}}
      {{- end }}
    compute:
      {{- include "autoscaler.computeSettings" . | nindent 8}}
