{{- if .Values.autoscaler.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autoscaler.fullname" . }}
  labels:
    {{- include "autoscaler.labels" . | nindent 4}}

  {{- with .Values.autoscaler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
